###
# [Register User] success
POST http://localhost:3000/api/users/register
Content-Type: application/json

{
  "first_name": "Harvey",
  "last_name": "Aparece",
  "username": "harapa1",
  "email": "harapa@test.com",
  "password": "password"
}

###
# [Register User] error
POST http://localhost:3000/api/users/register
Content-Type: application/json

{
}

###
# [Update User] success
POST http://localhost:3000/api/users/update
Content-Type: application/json
Accept: application/json

{
  "id": 1,
  "user": {
    "type": 0
  }
}

###
# [All Users] success
GET http://localhost:3000/api/users/all

###
# [Get one User] success
GET http://localhost:3000/api/users/10

###
# [Authenticate User]
POST http://localhost:3000/api/auth/login
Content-Type: application/json
Accept: application/json

{
  "usercred": "raven",
  "password": "password"
}


# [ All Company ]
###
GET http://localhost:3000/api/company/all

# [ Register Company ]
###
POST http://localhost:3000/api/company/register
Accept: application/json
Content-Type: application/json

{
  "company": {}
}

# Get authenticated User
###
GET http://localhost:3000/api/auth/authenticated

# Test signout
###
GET http://localhost:3000/api/auth/sign-out
