###
# [Register User] success
POST http://localhost:3000/api/users/register
Content-Type: application/json

{
  "first_name": "Harvey",
  "last_name": "Aparece",
  "username": "harapa1",
  "email": "harapa@test.com",
  "password": "password"
}

###
# [Register User] error
POST http://localhost:3000/api/users/register
Content-Type: application/json

{
}

###
# [Update User] success
POST http://localhost:3000/api/users/update
Content-Type: application/json
Accept: application/json

{
  "id": 1,
  "user": {
    "type": 0
  }
}

###
# [All Users] success
GET http://localhost:3000/api/users/all

###
# [Get one User] success
GET http://localhost:3000/api/users/10

###
# [Authenticate User]
POST http://localhost:3000/api/auth/login
Content-Type: application/json
Accept: application/json

{
  "usercred": "harapa",
  "password": "password"
}

###

# [Refresh token] getting new refresh tokens
POST http://localhost:3000/api/auth/refresh
Content-Type: application/json
Accept: application/json

{
  "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0LCJyZWZyZXNoIjpmYWxzZSwiaWF0IjoxNzIwMzcwMTQ0LCJleHAiOjE3MjAzNzEwNDR9.q01ENKpvNNEat4K2mZEvCU0y3l-k8nCqIZBWk9vuOQM"
}


# [ All Company ]
###
GET http://localhost:3000/api/company/all
